import { CompetitionSettings, LeaderboardManager, leaderboardCsv, normalizeName } from "./storage.js";
import { ArcadeEffects, animateNumber } from "./effects.js";
import { SeededRandom } from "./rng.js";
import { ACTIVE_SECONDS, COMPETITION_SECONDS, GAME_CONFIGS, TRANSITION_SECONDS, buildCompetition, buildGameOrder } from "./tasks.js";
import { MINIGAME_CLASSES } from "./minigames.js";
import { sumScores } from "./scoring.js";
import { StageGuard } from "./lifecycle.js";

const $=(selector,root=document)=>root.querySelector(selector);
const esc=value=>String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const requestedSeed=new URLSearchParams(location.search).get("seed");
const settings=new CompetitionSettings();
const createRunSeed=()=>`CEVA-${Date.now().toString(36).toUpperCase()}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36).toUpperCase()}`;
const app=$("#app"),modal=$("#modal"),modalContent=$("#modal-content"),leaderboard=new LeaderboardManager();

export class CompetitionManager {
  constructor({root=app,seed=requestedSeed||settings.getSeed()}={}){this.root=root;this.seed=seed;this.guard=new StageGuard();this.reset();}
  reset(){this.stopTimer();this.active?.cleanup();this.effects?.destroy();this.active=null;this.playerName="";this.index=-1;this.scores={};this.results=[];this.totalCorrect=0;this.totalAttempts=0;this.totalMistakes=0;this.transitioning=false;}
  landing(prefill="") {this.stopTimer();this.active?.cleanup();document.body.classList.add("menu-active");this.root.innerHTML=`<section class="menu-screen" aria-labelledby="menu-title"><div class="menu-content"><img class="menu-logo" src="assets/menu/logo-light.png" alt="CEVA Logistics"><h1 id="menu-title"><span>CHRISTMAS</span><strong>LOGISTICS CHALLENGE</strong></h1><p class="menu-details">9 GAMES <i>•</i> 3 MINUTES <i>•</i> 1,000 POINTS</p><form class="menu-form" id="start-form"><label class="visually-hidden" for="player-name">Participant name</label><div class="menu-input-wrap"><span aria-hidden="true"></span><input id="player-name" maxlength="24" value="${esc(prefill)}" autocomplete="name" placeholder="Enter your name..." autofocus></div><div class="menu-error" id="name-error" aria-live="polite"></div><button class="menu-start" type="submit"><i aria-hidden="true"></i><span>START GAME</span></button><button class="menu-leaderboard" type="button" id="leaderboard-button"><span aria-hidden="true">🏆</span> VIEW LEADERBOARD</button><button class="menu-organizer" type="button" id="organizer-button">Organizer tools</button></form></div></section>`;$("#start-form").onsubmit=event=>{event.preventDefault();const input=$("#player-name"),name=input.value.trim().replace(/\s+/g," ");if(!name){$("#name-error").textContent="Enter a participant name to begin.";return input.focus();}this.playerName=name;this.prepare();};$("#leaderboard-button").onclick=()=>showLeaderboard();$("#organizer-button").onclick=()=>showOrganizer();}
  prepare(){document.body.classList.remove("menu-active");this.scores={};this.results=[];this.totalCorrect=0;this.totalAttempts=0;this.totalMistakes=0;this.index=-1;this.runSeed=this.seed||createRunSeed();const rng=new SeededRandom(this.runSeed);this.gameConfigs=buildGameOrder(rng.fork("game-order"));this.tasks=buildCompetition(this.runSeed,rng);this.countdown(3);}
  countdown(value){if(value===0){this.root.innerHTML='<div class="countdown go">GO!</div>';this.transitionHandle=setTimeout(()=>{this.competitionStarted=performance.now();this.next();},500);return;}this.root.innerHTML=`<div class="countdown">${value}</div>`;this.transitionHandle=setTimeout(()=>this.countdown(value-1),850);}
  next(){if(this.transitioning)return;this.index++;if(this.index>=this.gameConfigs.length)return this.finish();this.startGame();}
  startGame(){this.transitioning=false;this.pendingResult=null;const config=this.gameConfigs[this.index],GameClass=MINIGAME_CLASSES[config.id];const token=this.guard.begin(config.time);this.deadline=this.guard.deadline;this.root.innerHTML=`<section class="competition-shell"><div class="competition-hud"><div><small>PLAYER</small><strong>${esc(this.playerName)}</strong></div><div><small>MINIGAME</small><strong>${this.index+1} / 9 · ${config.name}</strong></div><div><small>SCORE</small><strong id="score-value">${sumScores(this.scores)} / 1000</strong></div><div class="clock"><small>TIME</small><strong id="stage-time">${config.time.toFixed(1)}</strong></div></div><div class="overall"><span>COMPETITION REMAINING</span><div class="overall-progress"><i id="overall-bar"></i></div><b id="overall-time">180s</b></div><header class="minigame-head"><div><div class="eyebrow">CHALLENGE ${String(this.index+1).padStart(2,"0")}</div><h1>${config.name}</h1></div><div class="instruction-card"><strong>${config.action}</strong><span>${config.instruction}</span><small>${config.hint}</small></div></header><div class="minigame-root" id="minigame-root"></div><div class="score-flash" id="score-flash" aria-live="polite"></div></section>`;
    this.effects=new ArcadeEffects($("#minigame-root"));const context={root:$("#minigame-root"),data:this.tasks[config.id],config,remaining:()=>Math.max(0,(this.deadline-performance.now())/1000),flash:(symbol,text)=>this.flash(symbol,text),feedback:(kind,text,anchor)=>this.effects.feedback(kind,text,anchor),selection:text=>this.effects.selection(text),update:()=>this.updateHud(),finish:()=>this.completeGame(token)};
    this.active=new GameClass().init(context);this.active.render();this.active.start();this.stageToken=token;this.timer=setInterval(()=>{if(this.stageToken!==token)return;this.updateHud();if(performance.now()>=this.deadline)this.completeGame(token);},100);this.updateHud();}
  elapsedBeforeCurrent(){return this.gameConfigs.slice(0,this.index).reduce((sum,game)=>sum+game.time,0)+this.index*TRANSITION_SECONDS;}
  updateHud(){if(!this.active)return;const remaining=Math.max(0,(this.deadline-performance.now())/1000),elapsed=this.elapsedBeforeCurrent()+(this.gameConfigs[this.index].time-remaining),competitionRemaining=Math.max(0,COMPETITION_SECONDS-3-elapsed),percent=competitionRemaining/COMPETITION_SECONDS*100;const stage=$("#stage-time"),bar=$("#overall-bar"),overall=$("#overall-time");const scoreNode=$("#score-value"),liveScore=Math.min(this.gameConfigs[this.index].max,this.pendingResult?.score??this.active.score()),displayScore=Math.min(1000,sumScores(this.scores)+liveScore);if(scoreNode&&scoreNode.dataset.score!==String(displayScore)){scoreNode.dataset.score=String(displayScore);scoreNode.textContent=`${displayScore} / 1000`;scoreNode.classList.remove("score-changed");void scoreNode.offsetWidth;scoreNode.classList.add("score-changed");}if(stage){stage.textContent=remaining.toFixed(1);stage.classList.toggle("critical",remaining<5);}if(bar)bar.style.width=`${percent}%`;if(overall)overall.textContent=`${Math.ceil(competitionRemaining)}s`;}
  flash(symbol,text){const node=$("#score-flash");if(!node)return;node.textContent=`${symbol} ${text}`;node.classList.remove("show");requestAnimationFrame(()=>node.classList.add("show"));}

  completeGame(token=this.stageToken){if(this.transitioning||!this.guard.complete(token))return;this.transitioning=true;this.stopTimer();const config=this.gameConfigs[this.index],result=this.pendingResult||this.active.complete();this.active.cleanup();this.effects?.destroy();this.scores[config.id]=Math.min(config.max,result.score);this.results.push({...result,id:config.id,name:config.name,max:config.max});this.totalCorrect+=result.correct;this.totalAttempts+=result.attempts;this.totalMistakes+=result.mistakes;if(this.index===this.gameConfigs.length-1)return this.finish();const total=sumScores(this.scores);this.root.innerHTML=`<section class="stage-transition"><div class="eyebrow">${config.name} COMPLETE</div><strong>+${this.scores[config.id]}</strong><span>/ ${config.max} POINTS</span><div class="transition-track"><i></i></div><small>${this.index===this.gameConfigs.length-1?"CALCULATING FINAL RESULT":"NEXT: "+this.gameConfigs[this.index+1].name}</small><b>TOTAL ${total} / 1000</b></section>`;this.transitionHandle=setTimeout(()=>{this.transitioning=false;this.next();},TRANSITION_SECONDS*1000);}
  stopTimer(){if(this.timer)clearInterval(this.timer);this.timer=null;if(this.transitionHandle)clearTimeout(this.transitionHandle);this.transitionHandle=null;this.stageToken=null;this.guard?.cancel();}
  finish(){this.stopTimer();const score=sumScores(this.scores),previousRecord=leaderboard.getHighScore(),personalBest=Math.max(0,...leaderboard.getPlayerHistory(normalizeName(this.playerName)).map(run=>run.score||0)),accuracy=this.totalAttempts?Math.round(this.totalCorrect/this.totalAttempts*100):0,timestamp=new Date().toISOString(),run={name:this.playerName,normalizedName:normalizeName(this.playerName),score,accuracy,mistakes:this.totalMistakes,averageResponseTime:0,minigameScores:this.scores,timestamp,competitionSeed:this.runSeed};const board=leaderboard.saveRun(run),rank=board.findIndex(row=>row.normalizedName===run.normalizedName)+1;this.root.innerHTML=`<section class="results ${score>previousRecord?"new-record":""}"><div class="result-banner"><div><div class="eyebrow">${score>previousRecord?"🏆 NEW COMPETITION RECORD":"CHRISTMAS RUN COMPLETE"}</div><span class="hud-label">PLAYER</span><h1>${esc(this.playerName)}</h1></div><div class="title-badge">RUN SEED · ${esc(this.runSeed)}</div></div><div class="score-block"><div><span class="hud-label">FINAL SCORE</span><strong><span id="final-score">0</span><small> / 1000</small></strong></div><div class="rank">LOCAL RANK #${rank}<small>COMPETITION RECORD ${board[0]?.score||score}</small>${score>personalBest?"<em>PERSONAL BEST</em>":""}</div></div><div class="result-summary"><span>ACCURACY <b>${accuracy}%</b></span><span>MISTAKES <b>${this.totalMistakes}</b></span><span>CHALLENGES <b>9 / 9</b></span></div><div class="score-breakdown">${this.results.map(result=>`<div><span>${result.name}</span><b>${result.score} / ${result.max}</b><i><em style="width:${result.score/result.max*100}%"></em></i></div>`).join("")}</div><div class="result-actions"><button class="primary" id="return-start">RETURN TO START</button><button class="secondary" id="view-board">LOCAL LEADERBOARD</button></div></section>`;$("#return-start").onclick=()=>{const name=this.playerName;this.reset();this.landing(name);};$("#view-board").onclick=()=>showLeaderboard(run.normalizedName);animateNumber($("#final-score"),score,900);if(score>previousRecord)new ArcadeEffects(this.root).burst($(".score-block"));}
}

const manager=new CompetitionManager();
function showLeaderboard(current=""){const rows=leaderboard.getLeaderboard();$("#modal-kicker").textContent="LOCAL DEVICE LEADERBOARD";modalContent.innerHTML=`<h2>CHRISTMAS COMPETITION RESULTS</h2>${rows.length?`<div class="board-record">🏆 COMPETITION RECORD <b>${rows[0].score}</b></div>`:""}<p class="local-note">Stored on this computer only — not a centralized company leaderboard.</p>${rows.length?`<div class="table-wrap"><table class="leaderboard"><thead><tr><th>RANK</th><th>PLAYER</th><th>HIGH SCORE</th><th>ACCURACY</th><th>DATE & TIME</th></tr></thead><tbody>${rows.map((row,index)=>`<tr class="${index<3?`podium podium-${index+1}`:""} ${row.normalizedName===current?"current":""}"><td>${index+1}</td><td>${esc(row.name)}</td><td>${row.score}</td><td>${row.accuracy}%</td><td>${new Date(row.timestamp).toLocaleString("en-GB")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">NO COMPLETED RUNS ON THIS DEVICE</div>'}`;modal.showModal();}
function downloadCsv(){const blob=new Blob([leaderboardCsv(leaderboard.getLeaderboard())],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="ceva-christmas-leaderboard.csv";link.click();URL.revokeObjectURL(url);}
function showOrganizer(){const seed=settings.getSeed();$("#modal-kicker").textContent="ORGANIZER TOOLS";modalContent.innerHTML=`<h2>COMPETITION CONTROL</h2><p class="local-note">These settings apply only on this computer.</p><label class="field-label" for="competition-seed">FIXED COMPETITION SEED</label><input class="name-input" id="competition-seed" maxlength="40" value="${esc(seed)}"><p class="settings-help">Use one seed for the whole event so every participant receives identical challenges.</p><div class="organizer-actions"><button class="primary" id="save-seed">SAVE SEED</button><button class="secondary" id="export-results">EXPORT CSV</button><button class="danger" id="reset-results">RESET RESULTS</button></div><div id="organizer-status" class="error-text" aria-live="polite"></div>`;$("#save-seed").onclick=()=>{if(settings.setSeed($("#competition-seed").value)){manager.seed=settings.getSeed();$("#organizer-status").textContent="✓ Competition seed saved.";}};$("#export-results").onclick=downloadCsv;$("#reset-results").onclick=()=>{if(confirm("Delete every local competition result? This cannot be undone.")){leaderboard.clearLeaderboard();$("#organizer-status").textContent="✓ Local competition results cleared.";}};modal.showModal();}
$("#modal-close").onclick=()=>modal.close();$("#brand-link").onclick=event=>{event.preventDefault();if(manager.index>=0&&!manager.transitioning&&!confirm("End this competition run?"))return;const name=manager.playerName;manager.reset();manager.landing(name);};
manager.landing();
