import { LeaderboardManager, normalizeName } from "./storage.js";
import { DifficultyManager, TaskGenerator, TASK_TYPES, taskIsCorrect } from "./tasks.js";

const DEBUG = new URLSearchParams(location.search).has("debug");
const TOTAL_ROUNDS = 12;
const $ = (selector, root = document) => root.querySelector(selector);
const app = $("#app"), modal = $("#modal"), modalContent = $("#modal-content"), toast = $("#toast");
const leaderboard = new LeaderboardManager();
const generator = new TaskGenerator();
const esc = (value) => String(value).replace(/[&<>'"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const fmt = (n) => Number(n).toLocaleString("en-US");

class TimerManager {
  start(seconds,onTick,onEnd){this.stop();this.remaining=seconds;onTick(this.remaining);this.id=setInterval(()=>{this.remaining--;onTick(this.remaining);if(this.remaining<=0){this.stop();onEnd();}},1000);}
  stop(){if(this.id)clearInterval(this.id);this.id=null;}
}

class GameManager {
  constructor(){this.timer=new TimerManager();this.locked=false;this.previousTypes=[];this.playerName="";this.resetState();}
  resetState(){this.state={score:0,round:0,correctActions:0,mistakes:0,streak:0,bestStreak:0,responseTimes:[],completedRounds:0,incidentCount:0,currentTask:null,selected:new Set(),order:[],startedAt:0};}
  landing(prefill=""){
    this.timer.stop();this.locked=false;
    app.innerHTML=`<section class="landing"><div><div class="eyebrow">FINAL DISPATCH WINDOW · 24 DEC</div><h1>CHRISTMAS <span>LOGISTICS CHALLENGE</span></h1><p class="lede">Take control of the North Pole distribution floor. Audit WMS records, stop bad shipments, and clear the final dispatch queue under operational pressure.</p><div class="process"><span>PICK</span><span>VERIFY</span><span>PACK</span><span>LABEL</span><span>PALLETIZE</span><span>LOAD</span><span>RELEASE</span></div></div><form class="start-panel" id="start-form" novalidate><div class="panel-heading"><span>OPERATOR ACCESS</span><span>TERMINAL 04</span></div><label class="field-label" for="player-name">PLAYER NAME</label><input class="name-input" id="player-name" maxlength="24" autocomplete="name" value="${esc(prefill)}" placeholder="Enter operator name"><div class="error-text" id="name-error" aria-live="polite"></div><button class="primary full" type="submit">START SHIFT</button><button class="secondary full" type="button" id="leaderboard-button">LEADERBOARD</button><div class="station-list"><span>12 OPERATIONAL TASKS</span><span>1 FINAL DISPATCH</span><span>EST. SHIFT: 2–3 MIN</span></div></form></section>`;
    $("#start-form").addEventListener("submit",e=>{e.preventDefault();const input=$("#player-name");const clean=input.value.trim().replace(/\s+/g," ");if(!clean){$("#name-error").textContent="Player name is required.";input.focus();return;}if(clean.length>24){$("#name-error").textContent="Maximum 24 characters.";return;}this.playerName=clean;this.briefing();});
    $("#leaderboard-button").onclick=()=>showLeaderboard();
  }
  briefing(){app.innerHTML=`<section class="briefing"><div class="eyebrow">SHIFT ASSIGNMENT / ${esc(this.playerName.toUpperCase())}</div><h1>FINAL DISPATCH WINDOW</h1><p class="lede">Look fast. Find what is wrong. Correct answers build your streak.</p><div class="briefing-grid"><div><strong>12</strong><span>LIVE TASKS</span></div><div><strong>13</strong><span>FINAL CHECKPOINTS</span></div><div><strong>0</strong><span>TOLERANCE FOR GUESSING</span></div></div><button class="primary" id="ready">BEGIN COUNTDOWN</button></section>`;$("#ready").onclick=()=>this.countdown(3);}
  countdown(n){if(n<0){this.start();return;}app.innerHTML=`<div class="countdown" aria-live="assertive">${n===0?"GO":n}</div>`;setTimeout(()=>this.countdown(n-1),n===0?500:700);}
  start(){this.resetState();this.previousTypes=[];this.nextRound();}
  pickType(){let pool=TASK_TYPES.filter(t=>!this.previousTypes.slice(-3).includes(t));if(this.state.round<=3)pool=pool.filter(t=>!["pallet","loading","quality"].includes(t));if(this.state.round>=10)pool=pool.filter(t=>!["packing","wms"].includes(t));const type=pool[Math.floor(Math.random()*pool.length)];this.previousTypes.push(type);return type;}
  nextRound(){this.locked=false;this.state.selected=new Set();this.state.round++;if(this.state.round>TOTAL_ROUNDS){this.launchFinal();return;}const difficulty=DifficultyManager.forRound(this.state.round);this.state.currentTask=generator.generate(this.pickType(),difficulty);this.renderTask();}
  maybeIncident(continueShift){
    if(this.state.completedRounds<3||this.state.incidentCount>=2||Math.random()>.18){continueShift();return;}
    const events=[
      {title:"SCANNER OFFLINE",text:"The main scanner stopped.",correct:"USE SPARE SCANNER",wrong:"KEEP SCANNING",reward:3},
      {title:"PALLET DAMAGED",text:"A pallet was hit by a truck.",correct:"STOP AND CHECK",wrong:"LOAD IT NOW",reward:3},
      {title:"COUNT NOT READY",text:"The stock count is still loading.",correct:"WAIT FOR THE COUNT",wrong:"USE OLD COUNT",reward:3},
      {title:"TRUCK ARRIVED EARLY",text:"The dock check is not done.",correct:"FINISH THE CHECK",wrong:"LOAD IT NOW",reward:3}
    ];
    const event=events[Math.floor(Math.random()*events.length)];let resolved=false;this.state.incidentCount++;
    app.innerHTML=`<section class="briefing"><div class="eyebrow">QUICK CHECK · 04 SEC</div><h1>${event.title}</h1><p class="lede">${event.text}</p><div class="result-actions" style="justify-content:center"><button class="primary" data-incident="correct">${event.correct}</button><button class="secondary" data-incident="wrong">${event.wrong}</button></div></section>`;
    const finish=(correct)=>{if(resolved)return;resolved=true;clearTimeout(timeout);if(correct){this.state.score+=event.reward;notify(`+${event.reward} · INCIDENT CONTAINED`);}else{this.state.score=Math.max(0,this.state.score-5);this.state.mistakes++;this.state.streak=0;notify("−5 · WRONG CHOICE");}setTimeout(continueShift,450);};
    app.querySelector('[data-incident="correct"]').onclick=()=>finish(true);app.querySelector('[data-incident="wrong"]').onclick=()=>finish(false);const timeout=setTimeout(()=>finish(false),4000);
  }
  launchFinal(){this.locked=false;this.state.selected=new Set();this.state.currentTask=generator.generateFinal();this.renderTask(true);}
  hud(final=false){const best=leaderboard.getHighScore();return `<div class="hud"><div class="hud-cell"><span class="hud-label">OPERATOR</span><span class="hud-value">${esc(this.playerName.toUpperCase())}</span></div><div class="hud-cell"><span class="hud-label">SCORE</span><span class="hud-value" id="score">${fmt(this.state.score)}</span></div><div class="hud-cell"><span class="hud-label">STREAK / RECORD ${fmt(best)}</span><span class="hud-value">${this.state.streak?`×${Math.min(1.3,1+this.state.streak*.1).toFixed(1)}`:"—"}</span></div><div class="hud-cell"><span class="hud-label">TIME REMAINING</span><span class="hud-value timer" id="timer">00:${String(this.state.currentTask.difficulty.time).padStart(2,"0")}</span></div></div><div class="progress"><i style="width:${final?100:(this.state.round-1)/TOTAL_ROUNDS*100}%"></i></div>`;}
  renderTask(final=false){const t=this.state.currentTask;this.state.order=t.items?[...t.items]:[];this.state.startedAt=performance.now();if(DEBUG)console.log("Generated task",structuredClone(t));app.innerHTML=`<section class="game-shell">${this.hud(final)}<div class="task-head"><div><div class="eyebrow">${final?"FINAL CHRISTMAS SHIPMENT":`ROUND ${String(this.state.round).padStart(2,"0")} / ${TOTAL_ROUNDS}`} · TIER ${t.difficulty.tier}</div><h1>${esc(t.title)}</h1><p class="task-instruction">${esc(t.instruction)}</p></div><span class="round-code">TASK / ${esc(t.type.toUpperCase())}</span></div><div id="task-area"></div></section>`;
    this.renderTaskBody();
    this.bindSubmit();
    this.timer.start(t.difficulty.time,(remaining)=>this.tick(remaining),()=>this.submit(true));
  }
  renderTaskBody(){const t=this.state.currentTask,area=$("#task-area");if(t.mode==="order"){area.innerHTML=`<div class="order-board">${this.state.order.map((item,i)=>`<div class="order-item"><span class="position">${String(i+1).padStart(2,"0")}</span><strong>${esc(item.key)}</strong><span>${item.weight?`${item.weight} KG${item.fragile?" · FRAGILE":""}`:`STOP ${item.stop} · ${item.weight} KG`}</span><div class="order-controls"><button data-move="up" data-index="${i}" aria-label="Move ${esc(item.key)} up">↑</button><button data-move="down" data-index="${i}" aria-label="Move ${esc(item.key)} down">↓</button></div></div>`).join("")}</div>${this.footer()}`;area.querySelectorAll("[data-move]").forEach(b=>b.onclick=()=>this.move(Number(b.dataset.index),b.dataset.move));return;}
    area.innerHTML=`<div class="workspace">${t.panels.map(p=>this.panel(p)).join("")}</div>${this.footer()}`;
    area.querySelectorAll("[data-select]").forEach(el=>el.onclick=()=>this.select(el.dataset.select));
    if(t.mode==="final")area.querySelectorAll("[data-action]").forEach(el=>el.onclick=()=>this.submit(false,el.dataset.action));
  }
  panel(p){if(p.type==="table")return `<section class="data-panel"><div class="data-title">${esc(p.title)}</div><div class="table-wrap"><table><thead><tr>${p.columns.map(c=>`<th>${esc(c)}</th>`).join("")}</tr></thead><tbody>${p.rows.map(r=>`<tr class="${p.selectable?"selectable":""} ${r.key&&this.state.selected.has(r.key)?"selected":""}" ${p.selectable?`tabindex="0" role="checkbox" aria-checked="${this.state.selected.has(r.key)}" data-select="${esc(r.key)}"`:""}>${r.cells.map(c=>`<td>${esc(c)}</td>`).join("")}</tr>`).join("")}</tbody></table></div></section>`;
    return `<section class="data-panel"><div class="data-title">${esc(p.title)}</div><div class="data-list">${p.items.map(raw=>{const item=typeof raw==="string"?{key:raw,label:raw}:raw;return p.selectable?`<button class="list-item selectable ${this.state.selected.has(item.key)?"selected":""}" data-select="${esc(item.key)}" aria-pressed="${this.state.selected.has(item.key)}">${esc(item.label)}</button>`:`<span class="list-item">${esc(item.label||item.key)}</span>`}).join("")}</div></section>`;}
  footer(){const t=this.state.currentTask;if(t.mode==="final")return `<div class="task-footer"><span class="selection-count" id="count">${this.state.selected.size} WRONG DETAILS SELECTED</span><div class="final-actions"><button class="action-button hold" data-action="HOLD">HOLD SHIPMENT</button><button class="action-button release" data-action="RELEASE">RELEASE SHIPMENT</button></div></div>`;return `<div class="task-footer"><span class="selection-count" id="count">${t.mode==="order"?"USE ARROWS TO SET THE ORDER":`${this.state.selected.size} SELECTED`}</span><button class="primary" id="submit" ${t.mode!=="order"&&!this.state.selected.size?"disabled":""}>${esc(t.submitLabel)}</button></div>`;}
  select(key){if(this.locked)return;this.state.selected.has(key)?this.state.selected.delete(key):this.state.selected.add(key);this.renderTaskBody();this.bindSubmit();}
  move(index,direction){if(this.locked)return;const target=direction==="up"?index-1:index+1;if(target<0||target>=this.state.order.length)return;[this.state.order[index],this.state.order[target]]=[this.state.order[target],this.state.order[index]];this.renderTaskBody();this.bindSubmit();}
  bindSubmit(){const button=$("#submit");if(button)button.onclick=()=>this.submit();}
  tick(remaining){const el=$("#timer");if(!el)return;el.textContent=`00:${String(Math.max(0,remaining)).padStart(2,"0")}`;el.className=`hud-value timer ${remaining<5?"critical":remaining<10?"warn":""}`;}
  submit(timeout=false,action=null){if(this.locked)return;this.locked=true;this.timer.stop();const t=this.state.currentTask,elapsed=(performance.now()-this.state.startedAt)/1000;const selected=[...this.state.selected];const correct=!timeout&&taskIsCorrect(t,selected,this.state.order.map(x=>x.key),action);if(DEBUG)console.log("Validation",{selected,order:this.state.order,action,correct,solution:t.solution});this.state.responseTimes.push(elapsed);
    if(correct){this.state.correctActions++;this.state.streak++;this.state.bestStreak=Math.max(this.state.bestStreak,this.state.streak);const fastBonus=Math.min(3,Math.max(1,Math.ceil(this.timer.remaining/4)));const points=t.mode==="final"?15+fastBonus:8+fastBonus;this.state.score+=points;this.feedback(true,`+${points}`,t.mode==="final"?"SHIPMENT STOPPED":"CORRECT");}
    else{this.state.mistakes++;this.state.streak=0;const penalty=timeout?0:5;this.state.score=Math.max(0,this.state.score-penalty);this.feedback(false,penalty?"−5":"0",timeout?"TIME UP":t.mode==="final"&&action==="RELEASE"?"WRONG RELEASE":"WRONG");}
    if(t.mode!=="final"){this.state.completedRounds++;}
  }
  feedback(correct,points,label){const reveal=this.state.currentTask.mode==="order"?this.state.currentTask.solution.join(" → "):this.state.currentTask.solution.join(" · ");const box=document.createElement("div");box.className="feedback";box.innerHTML=`<div class="feedback-card ${correct?"correct":"wrong"}"><div class="result">${esc(points)}</div><h2>${esc(label)}</h2>${correct?"":`<p>EXPECTED: ${esc(reveal)}</p>`}<button class="primary" id="continue">${this.state.currentTask.mode==="final"?"COMPLETE SHIFT":"CONTINUE"}</button></div>`;document.body.append(box);const advance=()=>{if(!box.isConnected)return;box.remove();this.state.currentTask.mode==="final"?this.finish():this.maybeIncident(()=>this.nextRound());};$("#continue",box).onclick=advance;setTimeout(advance,850);}
  finish(){const attempts=this.state.correctActions+this.state.mistakes,accuracy=attempts?Math.round(this.state.correctActions/attempts*100):0,average=this.state.responseTimes.reduce((a,b)=>a+b,0)/Math.max(1,this.state.responseTimes.length);const run={name:this.playerName,normalizedName:normalizeName(this.playerName),score:this.state.score,accuracy,correctActions:this.state.correctActions,mistakes:this.state.mistakes,averageResponseTime:Number(average.toFixed(1)),bestStreak:this.state.bestStreak,roundsCompleted:this.state.completedRounds,timestamp:new Date().toISOString()};const board=leaderboard.saveRun(run),rank=board.findIndex(x=>x.normalizedName===run.normalizedName)+1,title=this.performanceTitle(run);app.innerHTML=`<section class="results"><div class="result-banner"><div><div class="eyebrow">SHIFT COMPLETE</div><h1 id="result-name"></h1></div><div class="title-badge">${esc(title)}</div></div><div class="score-block"><div><span class="hud-label">FINAL SCORE</span><strong>${fmt(run.score)}</strong></div><div class="rank">RANK #${rank}</div></div><div class="stats-grid"><div class="stat"><small>ACCURACY</small><strong>${accuracy}%</strong></div><div class="stat"><small>AVG RESPONSE</small><strong>${average.toFixed(1)}s</strong></div><div class="stat"><small>BEST STREAK</small><strong>${run.bestStreak}</strong></div><div class="stat"><small>MISTAKES</small><strong>${run.mistakes}</strong></div></div><div class="result-actions"><button class="primary" id="replay">PLAY AGAIN</button><button class="secondary" id="view-board">LEADERBOARD</button></div></section>`;$("#result-name").textContent=this.playerName;$("#replay").onclick=()=>this.briefing();$("#view-board").onclick=()=>showLeaderboard(run.normalizedName);}
  performanceTitle(r){if(r.accuracy>=95&&r.score>=130)return"NORTH POLE LOGISTICS MASTER";if(r.accuracy>=85)return"DISPATCH EXPERT";if(r.accuracy>=70)return"OPERATIONS SPECIALIST";if(r.accuracy>=50)return"INVENTORY CONTROLLER";return"WAREHOUSE ROOKIE";}
}

const game=new GameManager();
function showLeaderboard(current=game.playerName?normalizeName(game.playerName):""){const rows=leaderboard.getLeaderboard();$("#modal-kicker").textContent="LOCAL LEADERBOARD";modalContent.innerHTML=`<h2>SHIFT RECORDS</h2>${rows.length?`<div class="table-wrap"><table class="leaderboard"><thead><tr><th>RANK</th><th>PLAYER</th><th>SCORE</th><th>ACCURACY</th><th>AVG TIME</th></tr></thead><tbody>${rows.map((r,i)=>`<tr class="${r.normalizedName===current?"current":""}"><td>${i+1}</td><td class="player-cell"></td><td>${fmt(r.score)}</td><td>${r.accuracy}%</td><td>${r.averageResponseTime}s</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">NO COMPLETED SHIFTS RECORDED</div>`}`;rows.forEach((r,i)=>modalContent.querySelectorAll(".player-cell")[i].textContent=r.name);modal.showModal();}
function notify(message){toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800);}
$("#modal-close").onclick=()=>modal.close();$("#brand-link").onclick=e=>{e.preventDefault();if(game.state.round&&!game.locked&&!confirm("End the current shift and return to start?"))return;game.landing(game.playerName);};
document.addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&document.activeElement?.dataset.select){e.preventDefault();document.activeElement.click();}});
game.landing();

export { GameManager };
