/** Pointer-event drag controller shared by every physical warehouse interaction. */
export function attachPointerDrag({element,targets,container=document.body,onStart=()=>{},onMove=()=>{},onDrop=()=>{},onCancel=()=>{},hitPadding=10}){
  let state=null,frame=0;
  const targetList=()=>typeof targets==="function"?[...targets()]:[...targets];
  const hitTarget=(x,y)=>targetList().find(target=>{const r=target.getBoundingClientRect();return x>=r.left-hitPadding&&x<=r.right+hitPadding&&y>=r.top-hitPadding&&y<=r.bottom+hitPadding;})||null;
  const paint=()=>{frame=0;if(!state)return;state.ghost.style.transform=`translate3d(${state.x-state.originX}px,${state.y-state.originY}px,0)`;const target=hitTarget(state.x,state.y);if(target!==state.target){state.target?.classList.remove("drag-over");target?.classList.add("drag-over");state.target=target;}onMove({x:state.x,y:state.y,target,ghost:state.ghost});};
  const move=event=>{if(!state||event.pointerId!==state.id)return;event.preventDefault();state.x=event.clientX;state.y=event.clientY;if(!frame)frame=requestAnimationFrame(paint);};
  const finish=(event,cancelled=false)=>{if(!state||event.pointerId!==state.id)return;event.preventDefault();if(frame){cancelAnimationFrame(frame);frame=0;paint();}const current=state;state=null;current.target?.classList.remove("drag-over");targetList().forEach(target=>target.classList.remove("drop-ready"));element.classList.remove("drag-source");try{element.releasePointerCapture?.(event.pointerId);}catch{}cancelled?onCancel(current):onDrop({...current,target:current.target,x:event.clientX,y:event.clientY});current.ghost.remove();};
  const down=event=>{if(state||event.button!==0)return;event.preventDefault();const rect=element.getBoundingClientRect(),ghost=element.cloneNode(true);ghost.removeAttribute("id");ghost.classList.add("drag-ghost","dragging");Object.assign(ghost.style,{position:"fixed",left:`${rect.left}px`,top:`${rect.top}px`,width:`${rect.width}px`,height:`${rect.height}px`,margin:"0"});container.append(ghost);state={id:event.pointerId,ghost,target:null,originX:event.clientX,originY:event.clientY,x:event.clientX,y:event.clientY};element.classList.add("drag-source");targetList().forEach(target=>target.classList.add("drop-ready"));element.setPointerCapture?.(event.pointerId);onStart(state);};
  element.addEventListener("pointerdown",down);element.addEventListener("pointermove",move);element.addEventListener("pointerup",finish);element.addEventListener("pointercancel",event=>finish(event,true));element.addEventListener("lostpointercapture",event=>{if(state)finish(event,true);});
  return ()=>{if(frame)cancelAnimationFrame(frame);state?.ghost.remove();state?.target?.classList.remove("drag-over");targetList().forEach(target=>target.classList.remove("drop-ready"));element.classList.remove("drag-source");state=null;element.removeEventListener("pointerdown",down);element.removeEventListener("pointermove",move);element.removeEventListener("pointerup",finish);};
}
