import { CARRIERS } from "./tasks.js";
import { scoreClassification, scoreStandard } from "./scoring.js";

export class BaseMinigame {
  init(context){this.ctx=context;this.root=context.root;this.data=context.data;this.mistakes=0;this.correct=0;this.cleanups=[];this.locked=false;return this;}
  render(){}
  start(){}
  score(){return 0;}
  complete(){this.locked=true;return {score:this.score(),mistakes:this.mistakes,correct:this.correct,attempts:this.correct+this.mistakes};}
  listen(node,event,handler){node.addEventListener(event,handler);this.cleanups.push(()=>node.removeEventListener(event,handler));}
  timeout(handler,delay){const id=setTimeout(handler,delay);this.cleanups.push(()=>clearTimeout(id));return id;}
  cleanup(){this.locked=true;this.cleanups.splice(0).forEach(fn=>fn());}
  flash(points,text){this.ctx.flash(points,text);this.ctx.update();}
  get remaining(){return this.ctx.remaining();}
}

class RapidFind extends BaseMinigame {
  constructor(kind){super();this.kind=kind;}
  render(){this.index=0;this.draw();}
  draw(){const round=this.data.rounds[this.index%this.data.rounds.length],isBarcode=this.kind==="barcode";this.current=round;this.root.innerHTML=`<div class="focus-card"><span>${isBarcode?"SANTA’S BARCODE":"TARGET GIFT SKU"}</span><strong>${round.target}</strong></div><div class="${isBarcode?"barcode-grid":"inventory-grid"}">${round.options.map((value,index)=>`<button class="${isBarcode?"barcode-parcel":"stock-card"}" data-sku="${value}">${isBarcode?'<i class="barcode"></i>':`<small>LOC ${String(index+1).padStart(2,"0")}</small>`}<strong>${value}</strong>${isBarcode?'<span>CEVA GIFT</span>':'<span>READY</span>'}</button>`).join("")}</div>`;this.root.querySelectorAll("[data-sku]").forEach(button=>this.listen(button,"click",()=>this.choose(button.dataset.sku)));}
  choose(value){if(this.locked)return;if(value===this.current.target){this.correct++;this.index++;this.flash("+","GIFT FOUND");if(this.index>=this.data.rounds.length)return this.ctx.finish();this.draw();}else{this.mistakes++;this.flash("−","WRONG SKU");}}
  score(){return scoreStandard({correct:Math.min(this.correct,10),total:10,mistakes:this.mistakes,completed:this.correct>=10,timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),missed=Math.max(0,10-this.correct);return {...result,correct:this.correct,mistakes:this.mistakes+missed,attempts:10+this.mistakes,score:this.score()};}
}

export class SpeedPicking extends RapidFind{constructor(){super("picking");}}
export class BarcodeHunt extends RapidFind{constructor(){super("barcode");}}

export class ConveyorRush extends BaseMinigame {
  render(){this.index=0;this.active=null;this.dragging=false;this.settling=false;this.root.innerHTML=`<div class="conveyor"><div class="belt-lines"></div><div id="moving-parcel"></div></div><div class="chutes">${CARRIERS.map(carrier=>`<div class="carrier-zone" data-chute="${carrier}"><span>${carrier}</span><small>DROP MATCHING BOX HERE</small></div>`).join("")}</div>`;}
  start(){this.spawn();this.lastFrame=performance.now();const tick=now=>{if(this.locked)return;const seconds=(now-this.lastFrame)/1000;this.lastFrame=now;if(this.active&&!this.dragging&&!this.settling){this.x+=this.speed*seconds;this.position();const belt=this.root.querySelector(".conveyor");if(this.box&&belt&&this.x>belt.clientWidth)this.miss();}this.raf=requestAnimationFrame(tick);};this.raf=requestAnimationFrame(tick);this.cleanups.push(()=>cancelAnimationFrame(this.raf));}
  spawn(){if(this.locked||this.index>=this.data.parcels.length)return;this.active=this.data.parcels[this.index];this.x=-145;this.speed=95+this.index*9;const host=this.root.querySelector("#moving-parcel");host.innerHTML=`<div class="moving-box" data-moving-box><i aria-hidden="true">⠿</i><b>${this.active.carrier}</b><span>${this.active.id}</span><small>${this.active.gift}</small></div>`;this.box=host.firstElementChild;this.position();this.listen(this.box,"pointerdown",event=>this.grab(event));}
  position(){if(this.box&&!this.dragging)this.box.style.left=`${this.x}px`;}
  grab(event){if(!this.active||this.settling)return;event.preventDefault();const rect=this.box.getBoundingClientRect();this.dragging=true;this.pointerId=event.pointerId;this.offsetX=event.clientX-rect.left;this.offsetY=event.clientY-rect.top;this.box.setPointerCapture?.(event.pointerId);this.box.classList.add("dragging");Object.assign(this.box.style,{position:"fixed",left:`${rect.left}px`,top:`${rect.top}px`,width:`${rect.width}px`,height:`${rect.height}px`});this.listen(this.box,"pointermove",move=>this.drag(move));this.listen(this.box,"pointerup",up=>this.drop(up));this.listen(this.box,"pointercancel",up=>this.drop(up));document.querySelectorAll("[data-chute]").forEach(zone=>zone.classList.add("drop-ready"));}
  drag(event){if(!this.dragging||event.pointerId!==this.pointerId)return;this.box.style.left=`${event.clientX-this.offsetX}px`;this.box.style.top=`${event.clientY-this.offsetY}px`;const zone=this.zoneAt(event.clientX,event.clientY);document.querySelectorAll("[data-chute]").forEach(item=>item.classList.toggle("drag-over",item===zone));}
  zoneAt(x,y){this.box.style.pointerEvents="none";const zone=document.elementFromPoint(x,y)?.closest?.("[data-chute]")||null;this.box.style.pointerEvents="";return zone;}
  drop(event){if(!this.dragging||event.pointerId!==this.pointerId)return;const zone=this.zoneAt(event.clientX,event.clientY);this.dragging=false;document.querySelectorAll("[data-chute]").forEach(item=>item.classList.remove("drop-ready","drag-over"));if(zone)return this.sort(zone);this.box.classList.remove("dragging");Object.assign(this.box.style,{position:"absolute",top:"12%",width:"160px",height:"75%"});this.position();}
  sort(zone){if(!this.active||this.settling)return;this.settling=true;const correct=zone.dataset.chute===this.active.carrier;zone.classList.add(correct?"accepted":"rejected");this.box.classList.add(correct?"delivered":"misrouted");if(correct){this.correct++;this.flash("+","PERFECT SORT");}else{this.mistakes++;this.flash("−","WRONG CARRIER");}this.timeout(()=>{zone.classList.remove("accepted","rejected");this.advance();},240);}
  advance(){this.index++;this.active=null;this.settling=false;if(this.index>=this.data.parcels.length)return this.ctx.finish();this.spawn();}
  miss(){if(!this.active||this.settling)return;this.mistakes++;this.flash("−","MISSED BOX");this.advance();}
  score(){return scoreStandard({correct:this.correct,total:this.data.parcels.length,mistakes:this.mistakes,completed:this.correct===this.data.parcels.length,timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),missed=Math.max(0,this.data.parcels.length-this.correct-this.mistakes);return {...result,mistakes:this.mistakes+missed,attempts:this.data.parcels.length,score:this.score()};}
}

export class PackingTetris extends BaseMinigame {
  render(){this.cells=Array.from({length:this.data.rows},()=>Array(this.data.cols).fill(null));this.placed={};this.selected=null;this.draw();}
  draw(){const boxes=this.data.boxes.filter(box=>!this.placed[box.id]);this.root.innerHTML=`<div class="packing-layout"><section><div class="data-title">GIFT BOXES · DRAG OR CLICK</div><div class="shape-rack">${boxes.map(box=>`<button class="shape-box ${this.selected===box.id?"picked":""}" draggable="true" data-shape="${box.id}" style="--w:${box.w};--h:${box.h}"><strong>${box.id}</strong><span>${box.w} × ${box.h}</span></button>`).join("")||'<div class="all-sorted">PALLET FULLY PACKED ✓</div>'}</div></section><section><div class="data-title">SANTA’S PALLET · 8 × 5</div><div class="pallet-grid">${this.cells.flatMap((row,y)=>row.map((value,x)=>`<button class="pallet-cell ${value?"filled":""}" data-cell="${x}:${y}" data-owner="${value||""}"></button>`)).join("")}</div></section></div>`;this.root.querySelectorAll("[data-shape]").forEach(box=>{this.listen(box,"click",()=>{this.selected=box.dataset.shape;this.draw();});this.listen(box,"dragstart",event=>{this.selected=box.dataset.shape;event.dataTransfer.setData("text/plain",box.dataset.shape);});});this.root.querySelectorAll("[data-cell]").forEach(cell=>{this.listen(cell,"dragover",event=>{event.preventDefault();cell.classList.remove("valid-target","invalid-target");cell.classList.add(this.canPlace(this.selected,cell.dataset.cell)?"valid-target":"invalid-target");});this.listen(cell,"dragleave",()=>cell.classList.remove("valid-target","invalid-target"));this.listen(cell,"drop",event=>{event.preventDefault();this.place(event.dataTransfer.getData("text/plain")||this.selected,cell.dataset.cell);});this.listen(cell,"click",()=>this.place(this.selected,cell.dataset.cell));});}
  canPlace(id,coordinate){if(!id||this.placed[id])return false;const box=this.data.boxes.find(item=>item.id===id),[x,y]=coordinate.split(":").map(Number);return x+box.w<=this.data.cols&&y+box.h<=this.data.rows&&Array.from({length:box.h},(_,dy)=>Array.from({length:box.w},(_,dx)=>this.cells[y+dy][x+dx])).flat().every(value=>!value);}
  place(id,coordinate){if(!id||this.placed[id])return;const box=this.data.boxes.find(item=>item.id===id),[x,y]=coordinate.split(":").map(Number),valid=this.canPlace(id,coordinate);if(!valid){this.mistakes++;this.flash("−","BOX DOES NOT FIT");return;}for(let dy=0;dy<box.h;dy++)for(let dx=0;dx<box.w;dx++)this.cells[y+dy][x+dx]=id;this.placed[id]={x,y};this.correct++;this.selected=null;this.flash("+","BOX PACKED");this.draw();if(this.correct===this.data.boxes.length)this.timeout(()=>this.ctx.finish(),250);}
  score(){const occupied=this.cells.flat().filter(Boolean).length,total=this.data.boxes.reduce((sum,box)=>sum+box.w*box.h,0);return scoreStandard({correct:occupied,total,mistakes:this.mistakes,completed:this.correct===this.data.boxes.length,timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),missed=this.data.boxes.length-this.correct;return {...result,mistakes:this.mistakes+missed,attempts:this.data.boxes.length+this.mistakes,score:this.score()};}
}

export class WmsDetective extends BaseMinigame {
  render(){this.selected=new Set();this.root.innerHTML=`<div class="compare-note">Compare both codes — the system will not reveal which records are wrong.</div><div class="record-table"><div class="record-head"><span>LOCATION</span><span>WMS RECORD</span><span>ACTUAL SCAN</span></div>${this.data.rows.map(row=>`<button data-row="${row.id}"><span>${row.location}</span><strong>${row.expected}</strong><strong>${row.actual}</strong></button>`).join("")}</div><button class="lock-answer" id="lock-detective">LOCK ANSWER</button>`;this.listen(this.root.querySelector("#lock-detective"),"click",()=>this.ctx.finish());this.root.querySelectorAll("[data-row]").forEach(row=>this.listen(row,"click",()=>{this.selected.has(row.dataset.row)?this.selected.delete(row.dataset.row):this.selected.add(row.dataset.row);row.classList.toggle("selected");this.ctx.update();}));}
  score(){return scoreClassification({selected:[...this.selected],solution:this.data.solution,universe:this.data.rows.map(row=>row.id),timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete();const answers=new Set(this.data.solution);this.correct=this.data.rows.filter(row=>this.selected.has(row.id)===answers.has(row.id)).length;this.mistakes=this.data.rows.length-this.correct;return {...result,score:this.score(),correct:this.correct,mistakes:this.mistakes,attempts:this.data.rows.length};}
}

export class TruckLoading extends BaseMinigame {
  render(){this.slots=Array(this.data.pallets.length).fill(null);this.selected=null;this.draw();}
  deliveryLabel(pallet){const last=this.data.pallets.length;if(pallet.stop===last)return `STOP ${pallet.stop} · LAST DELIVERY · LOAD FIRST`;if(pallet.stop===1)return "STOP 1 · FIRST DELIVERY · LOAD LAST";return `STOP ${pallet.stop} · DELIVERY ${pallet.stop}`;}
  palletMarkup(pallet){return `<button class="load-pallet ${this.selected===pallet.id?"picked":""}" draggable="true" data-pallet-id="${pallet.id}"><i aria-hidden="true">⠿</i><b>${pallet.city}</b><span>${this.deliveryLabel(pallet)}</span></button>`;}
  draw(){const placed=new Set(this.slots.filter(Boolean)),available=this.data.pallets.filter(pallet=>!placed.has(pallet.id));this.root.innerHTML=`<div class="loading-guide"><strong>LAST DELIVERY → LOAD FIRST</strong><span>Deep inside the truck = unloaded last</span></div><div class="truck-scene"><div class="truck-cab">TRUCK<br>FRONT</div><div class="truck-body"><div class="load-arrow">LOAD FIRST · DEEPEST <b>←</b> <b>←</b> REAR DOOR</div><div class="truck-slots">${this.slots.map((id,index)=>{const pallet=this.data.pallets.find(item=>item.id===id);return `<div class="truck-slot" data-slot="${index}"><small>POSITION ${index+1}</small>${pallet?this.palletMarkup(pallet):"<span>DROP PALLET</span>"}</div>`;}).join("")}</div></div><div class="rear-door">OPEN<br>REAR</div></div><div class="pallet-yard"><span>PALLETS WAITING</span><div>${available.map(pallet=>this.palletMarkup(pallet)).join("")||"ALL PALLETS LOADED"}</div></div><button class="lock-answer" id="lock-loading" ${this.slots.some(id=>!id)?"disabled":""}>LOCK LOAD ORDER</button>`;this.listen(this.root.querySelector("#lock-loading"),"click",()=>this.ctx.finish());this.root.querySelectorAll("[data-pallet-id]").forEach(card=>{this.listen(card,"click",event=>{event.stopPropagation();this.selected=card.dataset.palletId;this.draw();});this.listen(card,"dragstart",event=>{this.selected=card.dataset.palletId;event.dataTransfer.setData("text/plain",this.selected);event.dataTransfer.effectAllowed="move";});});this.root.querySelectorAll("[data-slot]").forEach(slot=>{this.listen(slot,"dragover",event=>{event.preventDefault();slot.classList.add("active");});this.listen(slot,"dragleave",()=>slot.classList.remove("active"));this.listen(slot,"drop",event=>{event.preventDefault();this.place(event.dataTransfer.getData("text/plain")||this.selected,Number(slot.dataset.slot));});this.listen(slot,"click",()=>this.place(this.selected,Number(slot.dataset.slot)));});}
  place(id,index){if(!id)return;const old=this.slots.indexOf(id);if(old>=0)this.slots[old]=null;this.slots[index]=id;this.selected=null;this.flash("↕","PALLET LOADED");this.draw();}
  score(){const correct=this.slots.filter((id,index)=>id===this.data.solution[index]).length;return scoreStandard({correct,total:this.slots.length,mistakes:0,completed:correct===this.slots.length,timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),correct=this.slots.filter((id,index)=>id===this.data.solution[index]).length;return {...result,correct,mistakes:this.slots.length-correct,attempts:this.slots.length,score:this.score()};}
}

export class MemoryChallenge extends BaseMinigame {
  render(){this.selected=new Set();this.revealed=false;this.root.innerHTML=`<div class="memory-stage"><p>MEMORIZE THESE GIFTS</p><div class="gift-memory">${this.data.shipment.map(gift=>`<span>🎁 <b>${gift}</b></span>`).join("")}</div><strong>THE MANIFEST HIDES IN 4 SECONDS</strong></div>`;}
  start(){this.timeout(()=>this.hide(),4000);}
  hide(){if(this.locked)return;this.revealed=true;this.root.innerHTML=`<div class="memory-stage"><p>WHICH GIFTS WERE ON SANTA’S MANIFEST?</p><div class="memory-options">${this.data.options.map(gift=>`<button data-gift="${gift}">🎁 <b>${gift}</b></button>`).join("")}</div><button class="lock-answer" id="lock-memory">LOCK MANIFEST</button></div>`;this.listen(this.root.querySelector("#lock-memory"),"click",()=>this.ctx.finish());this.root.querySelectorAll("[data-gift]").forEach(button=>this.listen(button,"click",()=>{this.selected.has(button.dataset.gift)?this.selected.delete(button.dataset.gift):this.selected.add(button.dataset.gift);button.classList.toggle("selected");}));}
  score(){return scoreClassification({selected:[...this.selected],solution:this.data.shipment,universe:this.data.options,timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),answers=new Set(this.data.shipment),correct=this.data.options.filter(gift=>this.selected.has(gift)===answers.has(gift)).length;return {...result,correct,mistakes:this.data.options.length-correct,attempts:this.data.options.length,score:this.score()};}
}

export class QualityControl extends BaseMinigame {
  render(){this.selected=new Set();this.root.innerHTML=`<div class="quality-legend"><span>EXPECTED: VALID CARRIER LABEL</span><span>COMPLETE SKU</span><span>UNDAMAGED BOX</span></div><div class="quality-grid">${this.data.parcels.map(parcel=>`<button class="quality-box ${parcel.issue||""}" data-quality="${parcel.id}"><i></i><b>${parcel.id}</b><span>${parcel.issue==="wrong-label"?"OTHER":parcel.carrier}</span><small>${parcel.issue==="missing"?"SKU ———":parcel.issue==="wrong-sku"?"SKU-ERROR":parcel.sku}</small></button>`).join("")}</div><button class="lock-answer" id="lock-quality">LOCK QUALITY CHECK</button>`;this.listen(this.root.querySelector("#lock-quality"),"click",()=>this.ctx.finish());this.root.querySelectorAll("[data-quality]").forEach(box=>this.listen(box,"click",()=>{this.selected.has(box.dataset.quality)?this.selected.delete(box.dataset.quality):this.selected.add(box.dataset.quality);box.classList.toggle("selected");}));}
  score(){return scoreClassification({selected:[...this.selected],solution:this.data.solution,universe:this.data.parcels.map(parcel=>parcel.id),timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),answers=new Set(this.data.solution),correct=this.data.parcels.filter(parcel=>this.selected.has(parcel.id)===answers.has(parcel.id)).length;return {...result,correct,mistakes:this.data.parcels.length-correct,attempts:this.data.parcels.length,score:this.score()};}
}

export class FinalDispatch extends BaseMinigame {
  render(){this.selected=new Set();this.action=null;const {order,actual}=this.data;this.root.closest(".competition-shell")?.classList.add("final-stage");this.root.innerHTML=`<div class="final-alert">FINAL SLEIGH CLEARANCE · CHECK ALL DETAILS</div><div class="dispatch-compare"><section><h3>CHRISTMAS ORDER</h3><dl><dt>SHIPMENT</dt><dd>${order.id}</dd><dt>SKU</dt><dd>${order.sku}</dd><dt>QUANTITY</dt><dd>${order.quantity}</dd><dt>CARRIER</dt><dd>${order.carrier}</dd><dt>SERIALS</dt><dd>${order.serials} / ${order.serials}</dd></dl></section><section><h3>PACKED SHIPMENT</h3><dl><dt>SHIPMENT</dt><dd>${order.id}</dd><dt>SKU</dt><dd>${actual.sku}</dd><dt>QUANTITY</dt><dd>${actual.quantity}</dd><dt>CARRIER</dt><dd>${actual.carrier}</dd><dt>SERIALS</dt><dd>${actual.serials} / ${order.serials}</dd></dl></section></div><div class="final-issues">${this.data.options.map(issue=>`<button data-issue="${issue}">${issue}</button>`).join("")}</div><div class="dispatch-actions"><button data-action="HOLD">HOLD SHIPMENT</button><button data-action="RELEASE">RELEASE SHIPMENT</button></div>`;this.root.querySelectorAll("[data-issue]").forEach(button=>this.listen(button,"click",()=>{this.selected.has(button.dataset.issue)?this.selected.delete(button.dataset.issue):this.selected.add(button.dataset.issue);button.classList.toggle("selected");}));this.root.querySelectorAll("[data-action]").forEach(button=>this.listen(button,"click",()=>{this.action=button.dataset.action;this.root.querySelectorAll("[data-action]").forEach(item=>item.classList.toggle("selected",item===button));this.timeout(()=>this.ctx.finish(),180);}));}
  score(){const base=scoreClassification({selected:[...this.selected],solution:this.data.solution,universe:this.data.options,timeRemaining:this.remaining,timeLimit:this.ctx.config.time,max:180});return Math.min(200,base+(this.action===this.data.action?20:0));}
  complete(){const result=super.complete(),answers=new Set(this.data.solution),issueCorrect=this.data.options.filter(issue=>this.selected.has(issue)===answers.has(issue)).length,actionCorrect=this.action===this.data.action;return {...result,score:this.score(),correct:issueCorrect+(actionCorrect?1:0),mistakes:this.data.options.length-issueCorrect+(actionCorrect?0:1),attempts:this.data.options.length+1};}
  cleanup(){this.root.closest(".competition-shell")?.classList.remove("final-stage");super.cleanup();}
}

export const MINIGAME_CLASSES={picking:SpeedPicking,conveyor:ConveyorRush,barcode:BarcodeHunt,packing:PackingTetris,detective:WmsDetective,loading:TruckLoading,memory:MemoryChallenge,quality:QualityControl,final:FinalDispatch};
