import { CARRIERS } from "./tasks.js";
import { scoreClassification, scoreStandard } from "./scoring.js";

export class BaseMinigame {
  init(context){this.ctx=context;this.root=context.root;this.data=context.data;this.mistakes=0;this.correct=0;this.cleanups=[];this.locked=false;return this;}
  render(){}
  start(){}
  score(){return 0;}
  complete(){this.locked=true;return {score:this.score(),mistakes:this.mistakes,correct:this.correct,attempts:this.correct+this.mistakes};}
  listen(node,event,handler){node.addEventListener(event,handler);this.cleanups.push(()=>node.removeEventListener(event,handler));}
  timeout(handler,delay){const id=setTimeout(handler,delay);this.cleanups.push(()=>clearTimeout(id));return id;}
  cleanup(){this.locked=true;this.cleanups.splice(0).forEach(fn=>fn());}
  flash(points,text){this.ctx.flash(points,text);this.ctx.update();}
  get remaining(){return this.ctx.remaining();}
}

class RapidFind extends BaseMinigame {
  constructor(kind){super();this.kind=kind;}
  render(){this.index=0;this.draw();}
  draw(){const round=this.data.rounds[this.index%this.data.rounds.length],isBarcode=this.kind==="barcode";this.current=round;this.root.innerHTML=`<div class="focus-card"><span>${isBarcode?"SANTA’S BARCODE":"TARGET GIFT SKU"}</span><strong>${round.target}</strong></div><div class="${isBarcode?"barcode-grid":"inventory-grid"}">${round.options.map((value,index)=>`<button class="${isBarcode?"barcode-parcel":"stock-card"}" data-sku="${value}">${isBarcode?'<i class="barcode"></i>':`<small>LOC ${String(index+1).padStart(2,"0")}</small>`}<strong>${value}</strong>${isBarcode?'<span>CEVA GIFT</span>':'<span>READY</span>'}</button>`).join("")}</div>`;this.root.querySelectorAll("[data-sku]").forEach(button=>this.listen(button,"click",()=>this.choose(button.dataset.sku)));}
  choose(value){if(this.locked)return;if(value===this.current.target){this.correct++;this.index++;this.flash("+","GIFT FOUND");if(this.index>=this.data.rounds.length)return this.ctx.finish();this.draw();}else{this.mistakes++;this.flash("−","WRONG SKU");}}
  score(){return scoreStandard({correct:Math.min(this.correct,10),total:10,mistakes:this.mistakes,completed:this.correct>=10,timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),missed=Math.max(0,10-this.correct);return {...result,correct:this.correct,mistakes:this.mistakes+missed,attempts:10+this.mistakes,score:this.score()};}
}

export class SpeedPicking extends RapidFind{constructor(){super("picking");}}
export class BarcodeHunt extends RapidFind{constructor(){super("barcode");}}

export class ConveyorRush extends BaseMinigame {
  render(){this.index=0;this.active=null;this.root.innerHTML=`<div class="conveyor"><div class="belt-lines"></div><div id="moving-parcel"></div></div><div class="chutes">${CARRIERS.map(carrier=>`<button data-chute="${carrier}"><span>${carrier}</span><small>SORTING CHUTE</small></button>`).join("")}</div>`;this.root.querySelectorAll("[data-chute]").forEach(button=>this.listen(button,"click",()=>this.sort(button.dataset.chute)));}
  start(){this.spawn();}
  spawn(){if(this.locked||this.index>=this.data.parcels.length)return;this.active=this.data.parcels[this.index];const host=this.root.querySelector("#moving-parcel");host.innerHTML=`<button class="moving-box" style="--travel:${Math.max(2.4,4.8-this.index*.18)}s"><b>${this.active.carrier}</b><span>${this.active.id}</span><small>${this.active.gift}</small></button>`;const box=host.firstElementChild;this.listen(box,"animationend",()=>this.miss());}
  sort(carrier){if(this.locked||!this.active)return;if(carrier===this.active.carrier){this.correct++;this.flash("+","SORTED");}else{this.mistakes++;this.flash("−","WRONG CHUTE");}this.index++;this.active=null;if(this.index>=this.data.parcels.length)return this.ctx.finish();this.spawn();}
  miss(){if(!this.active)return;this.mistakes++;this.flash("−","MISSED GIFT");this.index++;this.active=null;if(this.index>=this.data.parcels.length)return this.ctx.finish();this.spawn();}
  score(){return scoreStandard({correct:this.correct,total:this.data.parcels.length,mistakes:this.mistakes,completed:this.correct===this.data.parcels.length,timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),missed=Math.max(0,this.data.parcels.length-this.correct-this.mistakes);return {...result,mistakes:this.mistakes+missed,attempts:this.data.parcels.length,score:this.score()};}
}

export class PackingTetris extends BaseMinigame {
  render(){this.cells=Array.from({length:this.data.rows},()=>Array(this.data.cols).fill(null));this.placed={};this.selected=null;this.draw();}
  draw(){const boxes=this.data.boxes.filter(box=>!this.placed[box.id]);this.root.innerHTML=`<div class="packing-layout"><section><div class="data-title">GIFT BOXES · DRAG OR CLICK</div><div class="shape-rack">${boxes.map(box=>`<button class="shape-box ${this.selected===box.id?"picked":""}" draggable="true" data-shape="${box.id}" style="--w:${box.w};--h:${box.h}"><strong>${box.id}</strong><span>${box.w} × ${box.h}</span></button>`).join("")||'<div class="all-sorted">PALLET FULLY PACKED ✓</div>'}</div></section><section><div class="data-title">SANTA’S PALLET · 8 × 5</div><div class="pallet-grid">${this.cells.flatMap((row,y)=>row.map((value,x)=>`<button class="pallet-cell ${value?"filled":""}" data-cell="${x}:${y}" data-owner="${value||""}"></button>`)).join("")}</div></section></div>`;this.root.querySelectorAll("[data-shape]").forEach(box=>{this.listen(box,"click",()=>{this.selected=box.dataset.shape;this.draw();});this.listen(box,"dragstart",event=>{this.selected=box.dataset.shape;event.dataTransfer.setData("text/plain",box.dataset.shape);});});this.root.querySelectorAll("[data-cell]").forEach(cell=>{this.listen(cell,"dragover",event=>{event.preventDefault();cell.classList.remove("valid-target","invalid-target");cell.classList.add(this.canPlace(this.selected,cell.dataset.cell)?"valid-target":"invalid-target");});this.listen(cell,"dragleave",()=>cell.classList.remove("valid-target","invalid-target"));this.listen(cell,"drop",event=>{event.preventDefault();this.place(event.dataTransfer.getData("text/plain")||this.selected,cell.dataset.cell);});this.listen(cell,"click",()=>this.place(this.selected,cell.dataset.cell));});}
  canPlace(id,coordinate){if(!id||this.placed[id])return false;const box=this.data.boxes.find(item=>item.id===id),[x,y]=coordinate.split(":").map(Number);return x+box.w<=this.data.cols&&y+box.h<=this.data.rows&&Array.from({length:box.h},(_,dy)=>Array.from({length:box.w},(_,dx)=>this.cells[y+dy][x+dx])).flat().every(value=>!value);}
  place(id,coordinate){if(!id||this.placed[id])return;const box=this.data.boxes.find(item=>item.id===id),[x,y]=coordinate.split(":").map(Number),valid=this.canPlace(id,coordinate);if(!valid){this.mistakes++;this.flash("−","BOX DOES NOT FIT");return;}for(let dy=0;dy<box.h;dy++)for(let dx=0;dx<box.w;dx++)this.cells[y+dy][x+dx]=id;this.placed[id]={x,y};this.correct++;this.selected=null;this.flash("+","BOX PACKED");this.draw();if(this.correct===this.data.boxes.length)this.timeout(()=>this.ctx.finish(),250);}
  score(){const occupied=this.cells.flat().filter(Boolean).length,total=this.data.boxes.reduce((sum,box)=>sum+box.w*box.h,0);return scoreStandard({correct:occupied,total,mistakes:this.mistakes,completed:this.correct===this.data.boxes.length,timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),missed=this.data.boxes.length-this.correct;return {...result,mistakes:this.mistakes+missed,attempts:this.data.boxes.length+this.mistakes,score:this.score()};}
}

export class WmsDetective extends BaseMinigame {
  render(){this.selected=new Set();this.root.innerHTML=`<div class="compare-note">Compare both codes — the system will not reveal which records are wrong.</div><div class="record-table"><div class="record-head"><span>LOCATION</span><span>WMS RECORD</span><span>ACTUAL SCAN</span></div>${this.data.rows.map(row=>`<button data-row="${row.id}"><span>${row.location}</span><strong>${row.expected}</strong><strong>${row.actual}</strong></button>`).join("")}</div><button class="lock-answer" id="lock-detective">LOCK ANSWER</button>`;this.listen(this.root.querySelector("#lock-detective"),"click",()=>this.ctx.finish());this.root.querySelectorAll("[data-row]").forEach(row=>this.listen(row,"click",()=>{this.selected.has(row.dataset.row)?this.selected.delete(row.dataset.row):this.selected.add(row.dataset.row);row.classList.toggle("selected");this.ctx.update();}));}
  score(){return scoreClassification({selected:[...this.selected],solution:this.data.solution,universe:this.data.rows.map(row=>row.id),timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete();const answers=new Set(this.data.solution);this.correct=this.data.rows.filter(row=>this.selected.has(row.id)===answers.has(row.id)).length;this.mistakes=this.data.rows.length-this.correct;return {...result,score:this.score(),correct:this.correct,mistakes:this.mistakes,attempts:this.data.rows.length};}
}

export class TruckLoading extends BaseMinigame {
  render(){this.order=[...this.data.pallets];this.dragFrom=null;this.draw();}
  draw(){const gap=index=>`<button class="load-gap" data-gap="${index}">DROP HERE</button>`;this.root.innerHTML=`<div class="load-label">TRUCK FRONT / LOADED FIRST</div><div class="load-order">${this.order.map((pallet,index)=>`${gap(index)}<button class="load-pallet ${this.dragFrom===index?"picked":""}" draggable="true" data-pallet="${index}"><b>${pallet.id}</b><span>STOP ${pallet.stop}</span><small>${pallet.city}</small></button>`).join("")}${gap(this.order.length)}</div><button class="lock-answer" id="lock-loading">LOCK LOAD ORDER</button>`;this.listen(this.root.querySelector("#lock-loading"),"click",()=>this.ctx.finish());this.root.querySelectorAll("[data-pallet]").forEach(card=>{const index=Number(card.dataset.pallet);this.listen(card,"click",()=>{this.dragFrom=index;this.draw();});this.listen(card,"dragstart",event=>{this.dragFrom=index;event.dataTransfer.effectAllowed="move";});});this.root.querySelectorAll("[data-gap]").forEach(gap=>{const boundary=Number(gap.dataset.gap);this.listen(gap,"dragover",event=>{event.preventDefault();gap.classList.add("active");});this.listen(gap,"dragleave",()=>gap.classList.remove("active"));this.listen(gap,"drop",event=>{event.preventDefault();this.move(boundary);});this.listen(gap,"click",()=>this.move(boundary));});}
  move(boundary){if(this.dragFrom==null)return;const [item]=this.order.splice(this.dragFrom,1),destination=boundary>this.dragFrom?boundary-1:boundary;this.order.splice(destination,0,item);this.dragFrom=null;this.flash("↕","PALLET MOVED");this.draw();}
  score(){const correct=this.order.filter((item,index)=>item.id===this.data.solution[index]).length;return scoreStandard({correct,total:this.order.length,mistakes:0,completed:correct===this.order.length,timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),correct=this.order.filter((item,index)=>item.id===this.data.solution[index]).length;return {...result,correct,mistakes:this.order.length-correct,attempts:this.order.length,score:this.score()};}
}

export class MemoryChallenge extends BaseMinigame {
  render(){this.selected=new Set();this.revealed=false;this.root.innerHTML=`<div class="memory-stage"><p>MEMORIZE THESE GIFTS</p><div class="gift-memory">${this.data.shipment.map(gift=>`<span>🎁 <b>${gift}</b></span>`).join("")}</div><strong>THE MANIFEST HIDES IN 4 SECONDS</strong></div>`;}
  start(){this.timeout(()=>this.hide(),4000);}
  hide(){if(this.locked)return;this.revealed=true;this.root.innerHTML=`<div class="memory-stage"><p>WHICH GIFTS WERE ON SANTA’S MANIFEST?</p><div class="memory-options">${this.data.options.map(gift=>`<button data-gift="${gift}">🎁 <b>${gift}</b></button>`).join("")}</div><button class="lock-answer" id="lock-memory">LOCK MANIFEST</button></div>`;this.listen(this.root.querySelector("#lock-memory"),"click",()=>this.ctx.finish());this.root.querySelectorAll("[data-gift]").forEach(button=>this.listen(button,"click",()=>{this.selected.has(button.dataset.gift)?this.selected.delete(button.dataset.gift):this.selected.add(button.dataset.gift);button.classList.toggle("selected");}));}
  score(){return scoreClassification({selected:[...this.selected],solution:this.data.shipment,universe:this.data.options,timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),answers=new Set(this.data.shipment),correct=this.data.options.filter(gift=>this.selected.has(gift)===answers.has(gift)).length;return {...result,correct,mistakes:this.data.options.length-correct,attempts:this.data.options.length,score:this.score()};}
}

export class QualityControl extends BaseMinigame {
  render(){this.selected=new Set();this.root.innerHTML=`<div class="quality-legend"><span>EXPECTED: VALID CARRIER LABEL</span><span>COMPLETE SKU</span><span>UNDAMAGED BOX</span></div><div class="quality-grid">${this.data.parcels.map(parcel=>`<button class="quality-box ${parcel.issue||""}" data-quality="${parcel.id}"><i></i><b>${parcel.id}</b><span>${parcel.issue==="wrong-label"?"OTHER":parcel.carrier}</span><small>${parcel.issue==="missing"?"SKU ———":parcel.issue==="wrong-sku"?"SKU-ERROR":parcel.sku}</small></button>`).join("")}</div><button class="lock-answer" id="lock-quality">LOCK QUALITY CHECK</button>`;this.listen(this.root.querySelector("#lock-quality"),"click",()=>this.ctx.finish());this.root.querySelectorAll("[data-quality]").forEach(box=>this.listen(box,"click",()=>{this.selected.has(box.dataset.quality)?this.selected.delete(box.dataset.quality):this.selected.add(box.dataset.quality);box.classList.toggle("selected");}));}
  score(){return scoreClassification({selected:[...this.selected],solution:this.data.solution,universe:this.data.parcels.map(parcel=>parcel.id),timeRemaining:this.remaining,timeLimit:this.ctx.config.time});}
  complete(){const result=super.complete(),answers=new Set(this.data.solution),correct=this.data.parcels.filter(parcel=>this.selected.has(parcel.id)===answers.has(parcel.id)).length;return {...result,correct,mistakes:this.data.parcels.length-correct,attempts:this.data.parcels.length,score:this.score()};}
}

export class FinalDispatch extends BaseMinigame {
  render(){this.selected=new Set();this.action=null;const {order,actual}=this.data;this.root.closest(".competition-shell")?.classList.add("final-stage");this.root.innerHTML=`<div class="final-alert">FINAL SLEIGH CLEARANCE · CHECK ALL DETAILS</div><div class="dispatch-compare"><section><h3>CHRISTMAS ORDER</h3><dl><dt>SHIPMENT</dt><dd>${order.id}</dd><dt>SKU</dt><dd>${order.sku}</dd><dt>QUANTITY</dt><dd>${order.quantity}</dd><dt>CARRIER</dt><dd>${order.carrier}</dd><dt>SERIALS</dt><dd>${order.serials} / ${order.serials}</dd></dl></section><section><h3>PACKED SHIPMENT</h3><dl><dt>SHIPMENT</dt><dd>${order.id}</dd><dt>SKU</dt><dd>${actual.sku}</dd><dt>QUANTITY</dt><dd>${actual.quantity}</dd><dt>CARRIER</dt><dd>${actual.carrier}</dd><dt>SERIALS</dt><dd>${actual.serials} / ${order.serials}</dd></dl></section></div><div class="final-issues">${this.data.options.map(issue=>`<button data-issue="${issue}">${issue}</button>`).join("")}</div><div class="dispatch-actions"><button data-action="HOLD">HOLD SHIPMENT</button><button data-action="RELEASE">RELEASE SHIPMENT</button></div>`;this.root.querySelectorAll("[data-issue]").forEach(button=>this.listen(button,"click",()=>{this.selected.has(button.dataset.issue)?this.selected.delete(button.dataset.issue):this.selected.add(button.dataset.issue);button.classList.toggle("selected");}));this.root.querySelectorAll("[data-action]").forEach(button=>this.listen(button,"click",()=>{this.action=button.dataset.action;this.root.querySelectorAll("[data-action]").forEach(item=>item.classList.toggle("selected",item===button));this.timeout(()=>this.ctx.finish(),180);}));}
  score(){const base=scoreClassification({selected:[...this.selected],solution:this.data.solution,universe:this.data.options,timeRemaining:this.remaining,timeLimit:this.ctx.config.time,max:180});return Math.min(200,base+(this.action===this.data.action?20:0));}
  complete(){const result=super.complete(),answers=new Set(this.data.solution),issueCorrect=this.data.options.filter(issue=>this.selected.has(issue)===answers.has(issue)).length,actionCorrect=this.action===this.data.action;return {...result,score:this.score(),correct:issueCorrect+(actionCorrect?1:0),mistakes:this.data.options.length-issueCorrect+(actionCorrect?0:1),attempts:this.data.options.length+1};}
  cleanup(){this.root.closest(".competition-shell")?.classList.remove("final-stage");super.cleanup();}
}

export const MINIGAME_CLASSES={picking:SpeedPicking,conveyor:ConveyorRush,barcode:BarcodeHunt,packing:PackingTetris,detective:WmsDetective,loading:TruckLoading,memory:MemoryChallenge,quality:QualityControl,final:FinalDispatch};
